version: 2.1
orbs:
  node: circleci/node@5.1.0

workflows:
  test-and-build:
    jobs:
      - ci_verify:
          filters:
            branches:
              ignore: 'changeset-release/main'
jobs:
  ci_verify:
    executor: node/default
    steps:
      - checkout
      - run: npm i -g pnpm
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm changeset status --since-main
