version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  test-and-build:
    jobs:
      - ci_verify:
          filters:
            branches:
              ignore: 'changeset-release/main'
jobs:
  ci_verify:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
      - run:
        command: npm i -g pnpm
      - run:
        command: pnpm build
      - run:
        command: pnpm lint
      - run:
        command: pnpm test
      - run:
        name: 'Check for required changesets'
        command: pnpm changeset status --since-main
