version: 2.1
orbs:
  node: circleci/node@5.0.2
workflows:
  test-and-build:
    jobs:
      - lint
jobs:
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
      - run:
        command: npm i -g pnpm
      - run:
        command: pnpm build
      - run:
        command: pnpm lint
