version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - restore_cache:
          key: pnpm-cache-v1-{{ checksum "pnpm-lock.yml" }}

      - run:
          name: 'Install dependencies'
          command: pnpm install

      - save_cache:
          key: pnpm-cache-v1-{{ checksum "pnpm-lock.yml" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  build:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Build'
          command: pnpm build

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  lint:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Verify code quality and formatting'
          command: pnpm lint

workflows:
  test-and-build:
    jobs:
      - setup:
          context: readonly-github-packages

      - build:
          requires:
            - setup

      - lint:
          requires:
            - build
