version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  setup:
    executor: node/default
    steps:
      - checkout

      - run:
          name: Install pnpm
          command: sudo npm i -g pnpm

      - restore_cache:
          key: pnpm-cache-v1-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Install dependencies
          command: pnpm install --no-frozen-lockfile

      - save_cache:
          key: pnpm-cache-v1-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  build:
    executor: node/default
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: pnpm build

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  lint:
    executor: node/default
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: pnpm lint

  test:
    executor: node/default
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: pnpm test

  changeset:
    executor: node/default
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run: pnpm changeset status --since-main

workflows:
  test-and-build:
    jobs:
      - setup:
          context: readonly-github-packages

      - build:
          requires:
            - setup

      # - test:
      #     requires:
      #       - build

      - lint:
          requires:
            - build

      - changeset:
          requires:
            - setup
          filters:
            branches:
              ignore: 'changeset-release/main'
